server:
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost/final?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver


      redis:
            #Redis服务器地址，默认localhost
            host: localhost
            #Redis服务器端口，默认6379
            port: 6379
            pool:
              #连接池最大连接数
              max-active: 8
              #最大阻塞等待时间，-1表示没有限制
              max-wait: -1
              #最大空闲连接
              max-idle: 8
              #最小空闲连接
              min-idle: 0
              #连接超时时间
              timeout: 0



  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: cn.psy.homework11.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level.cn.psy.homework11: debug
  path: /idea_workspace/homework11/AllLog